## Build-time configuration, injected by CI immediately before the export.
##
## THIS FILE IS CHECKED IN WITH EMPTY VALUES ON PURPOSE, AND THAT IS THE FIRST
## HALF OF THE "TELEMETRY ONLY ON itch" GUARANTEE.
##
## A build that was not produced by the itch workflow contains no endpoint at
## all — not a disabled one, not one behind a flag: the string is empty and
## there is nothing to POST to. That covers the GitHub Pages deploy, the
## Helios/tailnet container, every local `godot --path godot` run and every
## headless test, without any of them needing to opt out.
##
## The second half of the guarantee is a RUNTIME check in
## autoload/telemetry.gd (`_transmit_allowed`), which refuses to send unless
## the page is actually being served from itch. Two independent mechanisms,
## because either one alone has a hole: a stale or mis-scoped CI change could
## bake an endpoint into a Pages build, and conversely the itch build's files
## can be downloaded and re-hosted anywhere. Both must agree before a single
## request leaves.
##
## GENERATED by tools/write_build_config.sh — do not hand-edit, and never
## commit a populated copy.
class_name BuildConfig
extends RefCounted

## Telemetry collector URL. Empty = never transmit, log to the console instead
## (mirrors the TS build's behaviour when VITE_TELEMETRY_URL is unset).
const TELEMETRY_ENDPOINT := ""

## Git SHA of the exported commit. Empty = an unstamped local build; Tuning's
## own BUILD_VERSION is used instead.
const BUILD_SHA := ""
