# Mid-game pause + settings panel, tested as behaviour.
#
#   godot --headless --path godot tools/test_pause.tscn
#
# ui/start_overlay.gd's header used to argue there should be NO mid-game config
# route, because it means pausing, re-showing that layer over a captured mouse
# and restoring capture afterwards — the area where this project has already
# shipped an unplayable mobile build. The route exists now (look sensitivity and
# HUD size are only answerable by playing), so the argument becomes a test list.
# Everything here is one of the ways that decision could go wrong:
#
#   - the panel opening over the keypad, the start screen or the end card, and
#     two layers then fighting over the cursor. Guarded by ONE condition —
#     the player must actually hold input — which this pins from both sides.
#   - the medication meter draining behind the panel, so a player who opens
#     settings at three seconds left comes back reverted and possibly caught.
#   - the panel failing to give input back on RESUME, which strands the run.
#   - the randomize-codes row appearing mid-run, where flipping it would
#     either do nothing or silently reroll a code being read right now.
extends Node

var failures: Array[String] = []
var passes := 0

# Same reasoning as test_settings.gd's: a GDScript runtime error aborts only
# the function it happens in, so a suite can silently test less than it claims.
const EXPECTED_ASSERTIONS := 21

var _game: Node
var _overlay: CanvasLayer


func _check(cond: bool, what: String) -> void:
	if cond:
		passes += 1
	else:
		failures.append(what)


func _ready() -> void:
	_game = load("res://main.tscn").instantiate()
	add_child(_game)
	await get_tree().process_frame
	await get_tree().process_frame
	_overlay = _game.start_overlay

	_test_gate_before_admit()
	_test_open_and_shape()
	_test_meter_cannot_drain_while_paused()
	_test_resume_returns_control()
	_test_start_screen_still_shows_every_row()
	_restore()
	_finish()


# --- the gate ----------------------------------------------------------

func _test_gate_before_admit() -> void:
	# Before ADMIT ME the player does not hold input, so pause must refuse.
	# This is the same condition that keeps it off the keypad and the end card,
	# both of which take input away the same way — so pinning it here pins all
	# three without needing to drive a keypad.
	_check(
		not _game.player.is_input_enabled(),
		"precondition: the player must not hold input before ADMIT ME")
	_game._open_pause()
	_check(
		not get_tree().paused,
		"pause must REFUSE to open while the player has no input — otherwise it "
		+ "opens over the start screen, the keypad or the end card")
	_check(
		not _overlay._mid_game,
		"a refused pause must not leave the overlay in mid-game mode")


func _test_open_and_shape() -> void:
	# Drive the actual GUI button signal: the button consumes the click before
	# Player._unhandled_input, so Main must still request pointer capture from
	# its admit callback on hybrid iPad hardware.
	_overlay._admit_btn.emit_signal("pressed")
	_check(_game.player.is_input_enabled(), "ADMIT ME must hand input to the player")
	_check(_game.player._capture_attempted, "ADMIT ME captures a real pointer gesture")

	_game._open_pause()
	_check(get_tree().paused, "opening the pause panel must pause the tree")
	_check(
		not _game.player.is_input_enabled(),
		"the pause panel must take input off the player — that is also what releases the mouse")
	_check(_overlay.visible, "the overlay layer must be visible while paused")
	_check(_overlay._settings_panel.visible, "pause opens straight into the settings panel")
	_check(not _overlay._start_panel.visible, "pause must NOT show the start panel behind it")

	# The randomize-codes row is a per-run gameplay variable; the room's code is
	# already generated by the time this panel can be reached.
	_check(
		not _overlay._toggle_row.visible,
		"the randomize-codes row must be hidden mid-game")
	_check(
		not _overlay._toggle_rule.visible,
		"the separator above it must go with it, or the card ends on a rule ruling off nothing")
	_check(
		_overlay._done_btn.text == "RESUME",
		"the button must read RESUME mid-game, not DONE (got '%s')" % _overlay._done_btn.text)

	# Re-entrancy: a paused game cannot be paused again, because pausing is
	# what took input away.
	_game._open_pause()
	_check(get_tree().paused, "a second pause while paused must be a harmless no-op")


func _test_meter_cannot_drain_while_paused() -> void:
	# StateManager sets this in its own _ready precisely so the meter stops with
	# the tree. Asserted as the property rather than by advancing wall-clock
	# time, because a timing test here would be flaky for no extra coverage:
	# PROCESS_MODE_PAUSABLE is the whole mechanism.
	_check(
		StateManager.process_mode == Node.PROCESS_MODE_PAUSABLE,
		"StateManager must be PAUSABLE or the medication meter drains behind the "
		+ "pause panel and a player who opens settings at 3s left comes back reverted")
	# And the panel itself must be the exception, or its own RESUME button is
	# unclickable and the run is stuck behind a menu it cannot dismiss.
	_check(
		_overlay.process_mode == Node.PROCESS_MODE_ALWAYS,
		"the overlay must keep processing while paused, or RESUME cannot be pressed")


func _test_resume_returns_control() -> void:
	_overlay._on_done_pressed()
	_check(not get_tree().paused, "RESUME must unpause the tree")
	_check(_game.player.is_input_enabled(), "RESUME must give input back to the player")
	_check(
		not _overlay.visible,
		"RESUME must drop the whole overlay layer out of GUI picking, or it swallows "
		+ "the first click of the resumed run")


func _test_start_screen_still_shows_every_row() -> void:
	# The mid-game mode must not be sticky: opening CONFIGURATION from the title
	# card afterwards has to show the full panel again, randomize row included.
	_overlay._on_config_pressed()
	_check(
		_overlay._toggle_row.visible,
		"opening CONFIGURATION from the start screen must show the randomize-codes row again")
	_check(
		_overlay._done_btn.text == "DONE",
		"the button must read DONE again from the start screen (got '%s')" % _overlay._done_btn.text)


func _restore() -> void:
	get_tree().paused = false
	StateManager.reset()
	GameState.reset_run()


func _finish() -> void:
	var ran := passes + failures.size()
	if ran != EXPECTED_ASSERTIONS:
		failures.append(
			"expected %d assertions, %d ran — a runtime error almost certainly aborted a test "
			% [EXPECTED_ASSERTIONS, ran]
			+ "function silently (scroll up for SCRIPT ERROR)")

	print("")
	print("test_pause: %d assertion(s) passed" % passes)
	if failures.is_empty():
		print("  OK - the mid-game panel gates, pauses, and hands control back")
	else:
		for f in failures:
			print("  FAIL  %s" % f)
		print("  %d failure(s)" % failures.size())
	print("")
	get_tree().quit(0 if failures.is_empty() else 1)
