#!/usr/bin/env bash
# Generates godot/core/build_config.gd for an export.
#
#   tools/write_build_config.sh <telemetry-url> <git-sha>
#
# Called by .github/workflows/deploy-itch-godot.yml and by NOTHING ELSE. The
# Pages workflow and tools/deploy_tailnet.sh deliberately do not call it, so
# those builds keep the checked-in empty defaults and can never transmit — see
# the generated header below for why that is one of two independent gates
# rather than the only one.
#
# Both arguments may be empty, and with both empty this reproduces the
# checked-in file BYTE FOR BYTE. That is deliberate: it means
# `tools/write_build_config.sh "" "" && git diff --exit-code core/build_config.gd`
# is a real check that nobody has committed a populated config, and it is why
# the doc comment lives here rather than only in the checked-in copy.
set -euo pipefail

url="${1:-}"
sha="${2:-}"
cd "$(dirname "$0")/.."

# Refuse anything that is not a plain https URL. This is the last point at
# which a mistyped secret, an error page, or a shell-quoting accident is still
# cheap to catch — after this it is a string constant compiled into a wasm
# blob that has already been uploaded to itch.
if [ -n "$url" ]; then
  case "$url" in
    https://*) ;;
    *) echo "ERROR: telemetry URL must start with https:// (got '$url')" >&2; exit 1 ;;
  esac
  case "$url" in
    *[\'\"\\]*) echo "ERROR: telemetry URL contains quote/backslash characters" >&2; exit 1 ;;
  esac
fi
case "$sha" in
  *[!0-9a-fA-F]*) echo "ERROR: sha must be hex (got '$sha')" >&2; exit 1 ;;
esac

cat > core/build_config.gd <<EOF
## Build-time configuration, injected by CI immediately before the export.
##
## THIS FILE IS CHECKED IN WITH EMPTY VALUES ON PURPOSE, AND THAT IS THE FIRST
## HALF OF THE "TELEMETRY ONLY ON itch" GUARANTEE.
##
## A build that was not produced by the itch workflow contains no endpoint at
## all — not a disabled one, not one behind a flag: the string is empty and
## there is nothing to POST to. That covers the GitHub Pages deploy, the
## Helios/tailnet container, every local \`godot --path godot\` run and every
## headless test, without any of them needing to opt out.
##
## The second half of the guarantee is a RUNTIME check in
## autoload/telemetry.gd (\`_transmit_allowed\`), which refuses to send unless
## the page is actually being served from itch. Two independent mechanisms,
## because either one alone has a hole: a stale or mis-scoped CI change could
## bake an endpoint into a Pages build, and conversely the itch build's files
## can be downloaded and re-hosted anywhere. Both must agree before a single
## request leaves.
##
## GENERATED by tools/write_build_config.sh — do not hand-edit, and never
## commit a populated copy.
class_name BuildConfig
extends RefCounted

## Telemetry collector URL. Empty = never transmit, log to the console instead
## (mirrors the TS build's behaviour when VITE_TELEMETRY_URL is unset).
const TELEMETRY_ENDPOINT := "${url}"

## Git SHA of the exported commit. Empty = an unstamped local build; Tuning's
## own BUILD_VERSION is used instead.
const BUILD_SHA := "${sha}"
EOF

echo "build_config.gd written: endpoint=$([ -n "$url" ] && echo SET || echo EMPTY) sha=${sha:-none}"
